<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Properties extends Model
{
    protected $table = 'properties_all_data';

    protected $fillable = [
        'ListingKeyNumeric',
        'BathroomsFull',
        'BathroomsHalf',
        'BathroomsTotaltext',
        'BedroomsTotal',
        'BelowGradeFinishedArea',
        'BelowGradeFinishedAreaUnits',
        'BuildingAreaTotal',
        'City',
        'CoListAgentFullName',
        'CoListAgentKeyNumeric',
        'CoListAgentEmail',
        'CoListAgentDirectPhone',
        'CoListOfficeName',
        'CoListOfficePhone',
        'Cooling',
        'CountyOrParish',
        'DaysOnMarket',
        'Heating',
        'Latitude',
        'ListAgentFullName',
        'ListAgentKeyNumeric',
        'ListAgentEmail',
        'ListAgentDirectPhone',
        'ListOfficeName',
        'ListOfficePhone',
        'ListPrice',
        'Longitude',
        'MlsStatus',
        'PropertySubType',
        'PropertyType',
        'PublicRemarks',
        'StandardStatus',
        'StateOrProvince',
        'StreetDirPrefix',
        'StreetDirSuffix',
        'StreetName',
        'StreetNumber',
        'StreetSuffix',
        'UnitNumber',
        'YearBuilt',
        'AccessibilityFeatures',
        'Appliances',
        'AssociationAmenities',
        'Basement',
        'BuilderName',
        'BusinessName',
        'CarportSpaces',
        'CommonWalls',
        'CommunityFeatures',
        'ConstructionMaterials',
        'ElementarySchoolDistrict',
        'ExteriorFeatures',
        'FireplaceFeatures',
        'FoundationDetails',
        'GarageSpaces',
        'HighSchoolDistrict',
        'InteriorFeatures',
        'LandLeaseAmount',
        'LeaseTerm',
        'Levels',
        'LotFeatures',
        'LotSizeAcres',
        'LotSizeSquareFeet',
        'ParkingFeatures',
        'PatioAndPorchFeatures',
        'PetsAllowed',
        'PoolFeatures',
        'RoomsTotal',
        'Sewer',
        'StructureType',
        'SubdivisionName',
        'TaxLegalDescription',
        'Utilities',
        'WaterfrontFeatures',
        'WaterSource',
        'YardSize',
        'Zoning',
        'BuildingAreaTotalMetres',
        'BuildingAreaTotalSF',
        'DOMIncrementing',
        'DOMDate',
        'FootprintSQFT',
        'LotSizeNotCultivated',
        'LotSizeSeeded',
        'LotSizeTameHay',
        'LotSizeTreed',
        'LivingAreaMetres',
        'LivingAreaSF',
        'MainLevelFinishedAreaMetres',
        'MainLevelFinishedAreaSF',
        'UpperLevelFinishedAreaMetres',
        'UpperLevelFinishedAreaSF',
        'CondoName',
        'BedroomsBelowGrade',
        'CoListOfficeEmail',
        'ParkingEnclosed',
        'URL3DImage',
        'URLBrochure',
        'URLSoundByte',
        'FrontageFt',
        'HeatingExpense',
        'ListingContractDate',
        'ListingId',
        'ListingService',
        'InternetEntireListingDisplayYN',
        'OtherColumns',
        'diamond',
        'featured',
        'image_url'
    ];

    protected $casts = [
        'OtherColumns' => 'json',
    ];
}
